#!/bin/zsh

scriptName=$0

# newline for readability
echo

function commitAndDiff {
	for file in $(ls -Ap $1 | grep -v /); do
		if [[ $file != ${scriptName:2} ]]; then
			# store ls output for date comparison and coloring later
			localLsOutput=$(ls -l ~/$1$file 2> /dev/null)
			if [[ $? -eq 0 ]]; then
				# TODO: color the newer diff output green
				diffOutput=$(diff ~/$1$file $1$file)
				if [[ $? -eq 1 ]]; then
					if [[ ~/$1$file -nt $1$file ]]; then
						echo "local $1$file is newer, copy to here?"
						print -P "%F{green}$localLsOutput%f"
						ls -l $1$file
						echo $diffOutput
						# TODO: ask user for input
						# cp $1$file ~/$1
					else
						echo "github's $1$file is newer, not copying to here"
						echo $localLsOutput
						print -P "%F{green}$(ls -l $1$file)%f"
						echo $diffOutput
					fi
					echo
				fi
			fi
		fi
	done

	for dir in $(ls -Ap $1 | grep /); do
		if [[ $dir != ".git/" ]]; then
			ls -d ~/$1$dir &> /dev/null
			if [[ $? -eq 0 ]]; then
				commitAndDiff $1$dir
			fi
		fi
	done
}

commitAndDiff
